version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    port:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    command: sh ./entrypoint.sh